config/routes.rb
Rails.application.routes.draw do
  get 'frames/index'
  get 'testing/index'
  get 'welcome/index'

  resources :articles do
  	collection do 
  		get 'say_hello' => "articles#say_hello"
  	end 
  end

  root 'welcome#index'
  # root 'frames#index'

get '/button', to: 'your_controller_name#button', as: 'button'

end

app/models/Pages/LtTest.rb
require "selenium-webdriver"
require "test/unit"

module LtTest
 

def  test_footer_columns # ****

    # @driver.get("#{VAR1}")
    @driver.get("#$global_variable")


    # @driver.get('http://ya.ru/')
    @driver.manage.window.maximize  


end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord::Base
  validates :title, presence: true,
                    length: { minimum: 5 }

 # before_action :articles


# @employee = Articles.last

# puts @employee

end

app/models/get_files.rb
require_relative "testing"

app/models/testing.rb
#!/usr/bin/env ruby

# require 'test_helper'

require "selenium-webdriver"
require "test/unit"
require_relative "Pages/LtTest"
 
class LoginClass < Test::Unit::TestCase

 $global_variable = "https://google.ru"
 

include LtTest



  def setup

    Selenium::WebDriver::Chrome.driver_path = "/usr/local/bin/chromedriver"
    options = Selenium::WebDriver::Chrome::Options.new
    # options.add_argument('--headless')
    options.add_argument('--ignore-certificate-errors')
    options.add_argument('--disable-popup-blocking')
    options.add_argument('--disable-translate')
    options.add_argument('/usr/bin/google-chrome')
    @driver = Selenium::WebDriver.for :chrome, options: options


  end
 
  def starts
    # @logintest = LogintTest.new('test')
  end

  # def show
  #   @article = Article.find(params[:id])
  # end

  def teardown
    @driver.quit
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

 # include Response
 # before_action :articles

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

def edit
  @article = Article.find(params[:id])
end

  def say_hello
    fork { exec ('ruby ./app/models/testing.rb')}
    # fork { exec ('ruby ./test/Ruby_sel/runtest.rb')}
    render json: {"message": "hui"}

  end

  def new
      @article = Article.new
  end

def update
  @article = Article.find(params[:id])

  if @article.update(article_params)
    redirect_to @article
  else
    render 'edit'
  end
end

def destroy
  @article = Article.find(params[:id])
  @article.destroy

  redirect_to articles_path
end


def create
  @article = Article.new(article_params)

  if @article.save
    redirect_to @article
  else
    render 'new'
  end
end

# private

  def article_params
    params.require(:article).permit(:title, :text)
  end



end

app/controllers/frames_controller.rb
class FramesController < ApplicationController
  def index
  end
end

app/controllers/testing_controller.rb
# require './test/Ruby_sel/runtest' 

class TestingController < ApplicationController

	# def initialize
	# 	# @items = Array.new
	# 	@articles = Article.new
	# end

def initialize
  @article = Article.new(article_params)

  if @article.save
    redirect_to @article
  else
    render 'new'
  end
end

private

  def article_params
    params.require(:article).permit(:title, :text)
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @articles = Article.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/frames_helper.rb
module FramesHelper
end

app/helpers/testing_helper.rb
module TestingHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/button.html.erb
 <%#= button_to 'Press me', button_path, method: :get  %> 

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= form_with(model: @article, local: true) do |form| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<!--   <p>
    <%#= form.label :title %><br>
    <%#= form.text_field :title %>
  </p>
 -->
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

<%= link_to 'Back', root_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="2"></th>
  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
     <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<%= form_with scope: :article, url: articles_path, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/articles/show.html.erb
<!-- <p>
  <strong>Title:</strong>
  <%#= @article.title %>
</p> -->

<p>
  <strong>Text coordinate:</strong>
  <%= @article.text %>
</p>

<p>
<button onclick="sayHello();">Hi</button>
</p>

<%= link_to 'Back', root_path %>

app/views/frames/index.html.erb
<h1>Frames#index</h1>
<div>
<input id="myInput" type="text" name="urlsite" value="">
<button name="oklink">OK</button>
</div>
<!-- <iframe width="1040" height="800" src="http://localhost:3000/welcome/index" ></iframe> -->
<script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.min.js"></script>



<iframe id="iframes" src="http://localhost:3000/welcome/index" width="1240" height="800" ></iframe>
<!-- <iframe id="iframes" src="" width="1240" height="800" ></iframe> -->



<script type="text/javascript">

window.onload = function() {
	var oFrame = document.getElementById("iframes");
	oFrame.contentWindow.document.onclick = function(e) {
		console.log(e.clientX + ':' + e.clientY);
	};
}; 

$( "button" ).on( "click", function() {
  // console.log( $( this ).text() );
 var inputVal = document.getElementById('myInput').value;


$('iframe').attr('src', inputVal);
});



</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Job</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/testing/index.html.erb
<h1>Testing#index</h1>
<p>Find me in app/views/testing/index.html.erb</p>

app/views/welcome/button.html.erb
<%#= button_to 'Press me', button_path, method: :get %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>

<h3>Run file:</h3>
<a href="">run</a>

<script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script type="text/javascript">
	function sayHello() {
		$.getJSON("/articles/say_hello", function(res) {
			// alert(res);
		});
	}
</script>

<h1>Listing articles</h1>
<button onclick="sayHello();">Hi</button>


<table>
  <tr>
    <!-- <th>Title</th> -->
    <th>Text coordinate</th>
    <th colspan="2"></th>
  </tr>

  <% @articles.each do |article| %>
    <tr>
      <!-- <td><%#= article.title %></td> -->
      <td><%= article.text %></td>
     <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

	<%= link_to "somewhere", button_to %>